### ISSUE TITLE
Trench Whistle unusable when Whistle is in inventory

### ISSUE THREAD

**Issue by rundabollen** [ZluskeN/zsn_visselpipa#8]
**Description**
Having the Whistle (`ZSN_Whistle`) and the Trench Whistle (`ZSN_TrenchWhistle`) in the player's inventory only gives player the two whistle options for `ZSN_Whistle`.
**Expected Behavior**
To see a double set of the actions _Blow Whistle_ and _Blast Whistle_ for each respective whistle type.
**Steps to reproduce**
1. Put both whistle types in player's inventory (order of pickup does not matter)
2. Attempt to use whistle actions for both whistles and note how only the actions for `ZSN_Whistle`
 show up. (One can only tell the difference via sound).

**Comment by rundabollen** [comment]
Recommend lowest degree of issue severity label possible. Possible use cases for this functionally is probably limited to say the least.

**Comment by ZluskeN** [comment]
Known bug, I was hoping nobody would notice 🙄

**Comment by ZluskeN** [comment]
resolved
